Add a step for cabal check

diff --git a/.github/workflows/haskell-docs.yml b/.github/workflows/haskell-docs.yml
--- a/.github/workflows/haskell-docs.yml
+++ b/.github/workflows/haskell-docs.yml
@@ -21,10 +21,14 @@ jobs:
         with:
           ghc-version: '9.10.3'
           cabal-version: '3.14.2.0'
-      - name: Compile library to docs
+      - name: Check cabal file
         run: |
           cd $GITHUB_WORKSPACE/clash-shockwaves
           ghc --version
+          cabal check || echo "::warning title=Cabal check failed::cabal check reported issues"
+      - name: Compile library to docs
+        run: |
+          cd $GITHUB_WORKSPACE/clash-shockwaves
           cabal haddock --builddir ./hackage-dist --haddock-for-hackage --enable-doc --minimize-conflict-set
       - name: Upload Haddock docs
         uses: actions/upload-artifact@v4
